Replace all embeds with Vals and remove references to `set`
val-town/val-town-docs pull request #59
Opened 2023-12-15 19:38 UTC by Xkonti

Sections to go complete:
- [ ] Types of vals
- [ ] Reference
- [ ] Standard library
- [ ] Toubleshooting
- [ ] Guides
- [ ] Integrations
- [ ] REST API
- [ ] Contact

2023-12-18 14:03 UTC, stevekrouse commented
This is awesome! Thanks so much @Xkonti ❤️

2023-12-18 22:15 UTC, Xkonti commented
Nearly all the docs updated with exception of those mentioned in the description. I think it would be good to create PRs for:
- Guides / Saving data from a web page
- Integrations / Discord welcome bot
- Integrations / SQLite wasm

2023-12-20 17:48 UTC, stevekrouse commented on src/content/docs/api/aliases.mdx
> +  // token: @me.secrets.valtownToken,
```suggestion
  // for private vals, pass your val town api token
  // token: Deno.env.get('valtown')
```

2023-12-20 17:49 UTC, stevekrouse commented on src/content/docs/api/eval.mdx
> +[`https://api.val.town/v1/eval/@stevekrouse.add(@stevekrouse.example1, @stevekrouse.example2)`](https://api.val.town/v1/eval/@stevekrouse.add(@stevekrouse.example1,%20@stevekrouse.example2)).
This `@` syntax is no longer supported so this doesn't work anymore. Probably easiest to remove this line.

2023-12-20 17:49 UTC, stevekrouse commented on src/content/docs/api/my-resources.mdx
> +    Authorization: `Bearer ${Deno.env.get("valtownToken")}`,
```suggestion
    Authorization: `Bearer ${Deno.env.get("valtown")}`,
```

2023-12-20 17:50 UTC, stevekrouse commented on src/content/docs/api/vals.mdx
> +  token: Deno.env.get("valtownToken"),
```suggestion
  token: Deno.env.get("valtown"),
```

2023-12-20 17:50 UTC, stevekrouse commented on src/content/docs/api/vals.mdx
> +  token: Deno.env.get("valtownToken"),
```suggestion
  token: Deno.env.get("valtown"),
```

2023-12-20 17:50 UTC, stevekrouse commented on src/content/docs/api/vals.mdx
> +  token: Deno.env.get("valtownToken"),
```suggestion
  token: Deno.env.get("valtown"),
```

2023-12-20 17:50 UTC, stevekrouse commented on src/content/docs/api/vals.mdx
> +        token: Deno.env.get("valtownToken"),
```suggestion
        token: Deno.env.get("valtown"),
```

2023-12-20 17:50 UTC, stevekrouse commented on src/content/docs/api/vals.mdx
> +  token: Deno.env.get("valtownToken"),
```suggestion
  token: Deno.env.get("valtown"),
```

2023-12-20 17:50 UTC, stevekrouse commented on src/content/docs/api/vals.mdx
> +  token: Deno.env.get("valtownToken"),
```suggestion
  token: Deno.env.get("valtown"),
```

2023-12-20 17:51 UTC, stevekrouse commented on src/content/docs/api/vals.mdx
> +  token: Deno.env.get("valtownToken"),
```suggestion
  token: Deno.env.get("valtown"),
```

2023-12-20 17:52 UTC, stevekrouse commented on src/content/docs/guides/hosted-puppeteer-browserless.mdx
> +  `https://chrome.browserless.io/scrape?token=${Deno.env.get("browserlessKey")}`,
```suggestion
  `https://chrome.browserless.io/scrape?token=${Deno.env.get("browserless")}`,
```

2023-12-20 17:52 UTC, stevekrouse commented on src/content/docs/guides/hosted-puppeteer-browserless.mdx
> +  browserWSEndpoint: `wss://chrome.browserless.io?token=${Deno.env.get("browserlessKey")}`,
```suggestion
  browserWSEndpoint: `wss://chrome.browserless.io?token=${Deno.env.get("browserless")}`,
```

2023-12-20 17:54 UTC, stevekrouse commented on src/content/docs/guides/save-html-form-data.mdx
> +  <form action="https://user-renderFormAndSaveData.web.val.run" method="post">
Import and use this function: https://www.val.town/v/stevekrouse/thisWebURL

```suggestion
  <form action="${thisWebURL()}" method="post">
```

2023-12-20 17:55 UTC, stevekrouse commented on src/content/docs/guides/web-scraping.mdx
> +
```suggestion
Outputs:
```

2023-12-20 17:55 UTC, stevekrouse commented on src/content/docs/integrations/Databases/upstash.mdx
> +const { Redis } = await import("npm:@upstash/redis");
make static import

2023-12-20 17:56 UTC, stevekrouse commented on src/content/docs/integrations/Databases/upstash.mdx
> +const { Redis } = await import("npm:@upstash/redis");
make static import

2023-12-20 21:30 UTC, stevekrouse commented on src/content/docs/integrations/GitHub/get-a-github-user.mdx
> +  const { Octokit } = await import("npm:@octokit/core");
convert to static import

2023-12-20 21:33 UTC, stevekrouse commented on src/content/docs/integrations/Google Sheets.mdx
> +export const gsheet_append_example = data["values"][0];
```suggestion
console.log(data["values"][0])
```

2023-12-20 21:34 UTC, stevekrouse commented on src/content/docs/integrations/airtable.mdx
> +);
convert to static import

2023-12-20 21:34 UTC, stevekrouse commented on src/content/docs/integrations/airtable.mdx
> +export const airtable_deno_sample = results;
```suggestion
console.log(results)
```

2023-12-20 21:35 UTC, stevekrouse commented on src/content/docs/integrations/telegram.mdx
> +const token = Deno.env.get("telegramBotToken");
```suggestion
```

2023-12-20 21:35 UTC, stevekrouse commented on src/content/docs/integrations/telegram.mdx
> +  token,
```suggestion
```

2023-12-20 21:36 UTC, stevekrouse commented on src/content/docs/integrations/telegram.mdx
> +    secret_token: token,
```suggestion
    secret_token: Deno.env.get("telegramBotToken"),
```

2023-12-20 21:38 UTC, stevekrouse commented on src/content/docs/types/http/routing.mdx
> +  const Peko = await import("https://deno.land/x/peko@2.0.0/mod.ts");
Covert to static import

2023-12-20 21:38 UTC, stevekrouse commented on src/content/docs/types/http/routing.mdx
> +  const { nhttp } = await import("npm:nhttp-land@1");
static import

2023-12-20 21:38 UTC, stevekrouse commented on src/content/docs/types/http/routing.mdx
> +  const { Router, json } = await import("npm:itty-router@4");
static import

2023-12-20 22:59 UTC, stevekrouse requested changes
Great work! A asked for a couple little nits, but looks good to go!

2023-12-20 23:46 UTC, Xkonti commented on src/content/docs/guides/web-scraping.mdx
> +
Hmm... `Outputs` is very generic. I would recommend on settling on 2 very distinct words:
- `Logs` - results of `console.log` which correspond to the `Logs` tab in the interface
- `Exports` - results of exporting a value from val

The code block below the val has a title `Logs` to indicate the output generated by `console.log`. It looks like this:
![image](https://github.com/val-town/val-town-docs/assets/5722272/67ad0363-a601-4bb1-967b-b05f9444d3b8)

2023-12-20 23:58 UTC, Xkonti commented
@stevekrouse All but one requested changes implemented. Please review the conversation about adding `Output`.

2023-12-21 13:42 UTC, stevekrouse commented on src/content/docs/guides/web-scraping.mdx
> +
Yeah that's perfect, ignore my comment then

2023-12-21 13:42 UTC, merged